name: Push Request on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Run Automated Tests
        run: npm test

      - name: Store Application Version
        run: echo "${{ github.run_number }}" > version.md

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
      - name: Ensure script is executable
        run: chmod +x dev.sh

      - name: Bump Version and Tag Docker Image
        run: |
          bash dev.sh
          docker build -t vedmastaren/test:${{ github.run_number }} .
          docker tag vedmastaren/test:${{ github.run_number }} vedmastaren/test:v${{ github.run_number }}
          docker push vedmastaren/test:${{ github.run_number }}
          docker push vedmastaren/test:v${{ github.run_number }}

      - name: Tag Repository Commit
        run: git tag v${{ github.run_number }}

      - name: Post to Slack on Success
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main by ${{ github.event.pusher.name }}: ${{ github.event.compare }}. No vulnerabilities found."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Post to Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main but it failed ${{ github.event.pusher.name }}: ${{ github.event.compare }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Run npm audit
        id: npm_audit
        run: |
          if npm audit --json | grep -q '"severity": "high"'; then
            echo "High severity vulnerabilities found"
            exit 1
          else
            echo "No high severity vulnerabilities found"
          fi

      - name: Post Audit Results to Slack
        if: failure()  # Kör detta steg endast om npm audit hittar sårbarheter
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: |
            :warning: npm audit found high vulnerabilities!
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
