name: Push Request on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Post to a Slack channel
        if: success()
        id: slack_success
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main by ${{ github.event.pusher.name }}: ${{ github.event.compare }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Post to a Slack channel
        if: failure()
        id: slack_failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main but it failed ${{ github.event.pusher.name }}: ${{ github.event.compare }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Run npm audit 
        id: npm_audit
        run: |
          if npm audit --json | grep -q '"severity": "high"'; then
            echo "High severity vulnerabilities found"
            exit 1
          else
            echo "No high severity vulnerabilities found"
          fi


      - name: Post Audit Results to Slack
        if: failure()  # Kör detta steg endast om npm audit hittar sårbarheter
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: |
            :warning: npm audit found high vulnerabilities!
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Post Success Message to Slack
        if: success()  # Kör detta steg om inga sårbarheter hittas
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main by ${{ github.event.pusher.name }}: ${{ github.event.compare }}. No vulnerabilities found."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}