name: Push Request on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install Dependencies
        run: npm install
        
      - name: Run test script
        run: npm test

      # Prompt for input to select bump type
      - name: Select Bump Type
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Which bump type would you like to perform? (major|minor|patch)"
          read BUMP_TYPE
          echo "::set-output name=bump_type::$BUMP_TYPE"

      # Step to bump version and update version.md
      - name: Bump Version and Update version.md
        if: github.ref == 'refs/heads/main'
        run: |
          ./bumpversion.sh ${{ steps.select_bump.outputs.bump_type }}
          git add version.md
          git commit -m "Bumped version"
          git push origin main

      - name: Build Docker Image
        env:
          IMAGE_TAG: $(cat version.md)
        run: |
          docker build -t myapp:$IMAGE_TAG .
          docker tag myapp:$IMAGE_TAG myapp:latest
          docker push myapp:$IMAGE_TAG
          docker push myapp:latest

      # Tag repository commit after successful deployment
      - name: Tag Repository Commit
        if: success() && github.ref == 'refs/heads/main'
        run: |
          git tag $(cat version.md)
          git push origin $(cat version.md)


      - name: Post to a Slack channel
        if: success()
        id: slack_success
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main by ${{ github.event.pusher.name }}: ${{ github.event.compare }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Post to a Slack channel
        if: failure()
        id: slack_failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main but it failed ${{ github.event.pusher.name }}: ${{ github.event.compare }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      # Requirement 2: Glöm inte att ta bort override i package.json rad 29,30 57,58
      - name: Run npm audit 
        id: npm_audit
        run: |
          if npm audit --json | grep -q '"severity": "high"'; then
            echo "High severity vulnerabilities found"
            exit 1
          else
            echo "No high severity vulnerabilities found"
          fi


      - name: Post Audit Results to Slack
        if: failure()  # Kör detta steg endast om npm audit hittar sårbarheter
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: |
            :warning: npm audit found high vulnerabilities!
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Post Success Message to Slack
        if: success()  # Kör detta steg om inga sårbarheter hittas
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main by ${{ github.event.pusher.name }}: ${{ github.event.compare }}. No vulnerabilities found."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}