name: Push Request on Main

on:
  push:
    branches:
      - pull

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run test script
        run: npm test

      - name: Extract bump type from commit message
        id: extract_bump_type
        run: echo "::set-output name=bump_type::$(git log --format=%B -n 1 ${{ github.sha }} | grep -oE 'major|minor|patch')"

      - name: Run version bump script
        run: bash bumpversion.sh ${{ steps.extract_bump_type.outputs.bump_type }}

      - name: Tag commit with new version
        run: git tag -a v$(grep -oP '(?<=Version:\s)\d+\.\d+\.\d+' "version.md") -m "Version $(grep -oP '(?<=Version:\s)\d+\.\d+\.\d+' "version.md")"

      - name: Push tag to GitHub
        run: git push origin --tags

      - name: Post to Slack on Success
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main by ${{ github.event.pusher.name }}: ${{ github.event.compare }}. No vulnerabilities found."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Post to Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main but it failed ${{ github.event.pusher.name }}: ${{ github.event.compare }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Run npm audit
        id: npm_audit
        run: |
          if npm audit --json | grep -q '"severity": "high"'; then
            echo "High severity vulnerabilities found"
            exit 1
          else
            echo "No high severity vulnerabilities found"
          fi

      - name: Post Audit Results to Slack
        if: failure()  # Kör detta steg endast om npm audit hittar sårbarheter
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: |
            :warning: npm audit found high vulnerabilities!
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
