name: Push Request on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run test script
        run: npm test

      - name: Select Bump Type
        id: select_bump
        if: github.ref == 'refs/heads/main'
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 HEAD)
          if [[ $COMMIT_MSG == "major"* ]]; then
            BUMP_TYPE="major"
          elif [[ $COMMIT_MSG == "minor"* ]]; then
            BUMP_TYPE="minor"
          elif [[ $COMMIT_MSG == "patch"* ]]; then
            BUMP_TYPE="patch"
          else
            echo "No valid bump type found in commit message, defaulting to patch."
            BUMP_TYPE="patch"
          fi
          echo "Selected BUMP_TYPE: $BUMP_TYPE"
          echo "::set-output name=bump_type::$BUMP_TYPE"

      - name: Bump Version and Update version.md
        if: github.ref == 'refs/heads/main'
        run: |
          chmod +x bumpversion.sh
          ./bumpversion.sh ${{ steps.select_bump.outputs.bump_type }}
          git add version.md
          git commit -m "Bumped version"
          git push origin main

      - name: Build Docker Image
        env:
          IMAGE_TAG: $(cat version.md)
        run: |
          docker build -t myapp:$IMAGE_TAG .
          docker tag myapp:$IMAGE_TAG myapp:latest
          docker push myapp:$IMAGE_TAG
          docker push myapp:latest

      - name: Tag Repository Commit
        if: success() && github.ref == 'refs/heads/main'
        run: |
          git tag $(cat version.md)
          git push origin $(cat version.md)

      - name: Post to Slack on Success
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main by ${{ github.event.pusher.name }}: ${{ github.event.compare }}. No vulnerabilities found."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Post to Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main but it failed ${{ github.event.pusher.name }}: ${{ github.event.compare }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Run npm audit
        id: npm_audit
        run: |
          if npm audit --json | grep -q '"severity": "high"'; then
            echo "High severity vulnerabilities found"
            exit 1
          else
            echo "No high severity vulnerabilities found"
          fi

      - name: Post Audit Results to Slack
        if: failure()  # Kör detta steg endast om npm audit hittar sårbarheter
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: |
            :warning: npm audit found high vulnerabilities!
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
