name: Push Request on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072YF4QUAJ'
          slack-message: "New push to main by <${{ github.event.pusher.html_url }}|${{ github.event.pusher.name }}>: ${{ github.event.pusher.html_url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
