name: build-and-deploy

on:
  push:
    branches:
      - dev
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Setting up job"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t vedmastaren/test .

    - name: Read version from version.md
      id: version
      run: echo "VERSION=$(cat version.md)" >> $GITHUB_ENV

    - name: Tag Docker image with version
      run: |
        docker tag vedmastaren/test:latest vedmastaren/test:${{ env.VERSION }}
        docker tag vedmastaren/test:latest vedmastaren/test:v${{ env.VERSION }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push vedmastaren/test:${{ env.VERSION }}
        docker push vedmastaren/test:v${{ env.VERSION }}

    - name: Add tag to commit
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    - run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
        git push https://github-actions:${GH_PAT}@github.com/Vedmastaren/DevOps1FE.git v${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    - name: Post Log in to Docker Hub
      run: echo "Docker Hub login step completed"

    - name: Post Checkout repository
      run: echo "Repository checkout step completed"

    - name: Complete job
      run: echo "Job completed"